### ISSUE TITLE
noob question

### ISSUE THREAD

**Issue by michapixel** [MaBecker/esp8266#1]
i'm having trouble flashing the latest 1.91.
btw: i do this under win 10 in a git bash, esptool is properly installed.
I have an esp-12e with 4mb, so i'm using
```
$ esptool.py --port COM3 --baud 460800 write_flash --flash_freq 80m --flash_mode qio --flash_size 32m 0x0000 boot_v1.6.bin 0x1000 espruino_esp8 266_user1.bin 0x3FC000 esp_init_data_default.bin 0x37E000 blank.bin
```
but then i'm not getting anything at all:
```
Micha@NEMESIS_II /E/ESP8622/Code/simplewifi
$ npm run repl

> simplewifi@0.0.0 repl e:\ESP8622\Code\simplewifi
> node ./scripts/repl

Connecting REPL...
espruino:  Espruino Command-line Tool 0.0.23
-----------------------------------

espruino:  Connecting to 'COM3'
espruino:  No result found - just got ""
espruino:  Connected

Press Ctrl-C again to exit
>espruino:
Exited with status 0
```
With the 1.89 version of yours it's working.

Why all the fuzz you say? I wanted to get a 0.96"OLED working with espruino, so i need Graphics et al, which is ripped of of the original binaries, if i got it right. 
I don't need any fancy stuff i just wanted to write some strings to the display, mainly temperature / humidity and maybe ip and connection details.

**Comment by michapixel** [comment]
uhhm i forgot to say: the 1.89 version does not work, at least not regarding my oled, but it gets flashed.

**Comment by MaBecker** [comment]
> i'm having trouble flashing the latest 1.91.
btw: i do this under win 10 in a git bash, esptool is properly installed.
I have an esp-12e with 4mb, so i'm using

esptool.py has a space 

>  0x1000 espruino_esp8 266_user1.bin

**Comment by michapixel** [comment]
yeah, this is copied from git bash, that's a linebreak, 
original line is: 
```
esptool.py --port COM3 --baud 460800 write_flash --flash_freq 80m --flash_mode qio --flash_size 32m 0x0000 boot_v1.6.bin 0x1000 espruino_esp8266_user1.bin 0x3FC000 esp_init_data_default.bin 0x37E000 blank.bin
```
which results in:
```
esptool.py v1.3
Connecting....
Running Cesanta flasher stub...
Flash params set to 0x004f
Wrote 4096 bytes at 0x0 in 0.1 seconds (337.8 kbit/s)...
Wrote 475136 bytes at 0x1000 in 10.8 seconds (352.5 kbit/s)...
Wrote 4096 bytes at 0x3fc000 in 0.1 seconds (344.9 kbit/s)...
Wrote 4096 bytes at 0x37e000 in 0.1 seconds (344.9 kbit/s)...
Leaving...
```
but when i repl in there i get:
```
$ npm run repl

> simplewifi@0.0.0 repl e:\ESP8622\Code\simplewifi
> node ./scripts/repl

Connecting REPL...
espruino:  Espruino Command-line Tool 0.0.23
-----------------------------------

espruino:  Connecting to 'COM3'
espruino:  No result found - just got ""
espruino:  Connected

Press Ctrl-C again to exit
>espruino:
Exited with status 0
```
with 1.89 i get the logo et.al. (with the same esptool line)

**Comment by MaBecker** [comment]
looks fine

    esptool.py --port COM3 --baud 460800 write_flash \
    --flash_freq 80m --flash_mode qio --flash_size 32m \
    0x0000 boot_v1.6.bin \
    0x1000 espruino_esp8266_user1.bin \
    0x3FC000 esp_init_data_default.bin \
    0x37E000 blank.bin 

Can you use the WebIDE in Chrome over COM3 ?

**Comment by michapixel** [comment]
btw: thanks for the quick answer. much appreciated.

**Comment by MaBecker** [comment]
I never tried the node stuff, just the WebIDE over Com or Wifi

**Comment by MaBecker** [comment]
for chatting use https://gitter.im/espruino/Espruino

**Comment by michapixel** [comment]
WebIDE does not work for me most of the time. It connects, but i cannot type anything or send code. actually i got it running once, but then something failed and that's it.

**Comment by MaBecker** [comment]
check `Settings - Communications - BAUD RATE to 115200 `

**Comment by michapixel** [comment]
already did. nada.

**Comment by MaBecker** [comment]
any hints for that in CONSOLE ?

**Comment by michapixel** [comment]
```
We have chrome.serial - not using 'serialport' module
serial_audio: Audio Sample rate : 48000
serial_audio: Audio Serial Baud 9600 Bit time 5
No navigator.bluetooth - Web Bluetooth not enabled
GET chrome.storage.sync = {"AUTO_SAVE_CODE":true,"BAUD_RATE":"115200","BLOCKLY_EXTENSIONS":"|bluetooth|robot|","BLOCKLY_LANGUAGE":"en","BLOCKLY_TO_JS":false,"BOARD_JSON_URL":"http://www.espruino.com/json","CODE":"var  on = false;\nsetInterval(function() {\n  on = !on;\n  LED1.write(on);\n}, 500);","COMPILATION":true,"COMPILATION_URL":"http://www.espruino.com:32766","ENABLE_Testing":false,"ENV_ON_CONNECT":true,"FONT_SIZE":12,"MINIFICATION_DeadCode":true,"MINIFICATION_LEVEL":"","MINIFICATION_Literal":true,"MINIFICATION_Mangle":true,"MINIFICATION_Unreachable":true,"MINIFICATION_Unused":true,"MODULE_AS_FUNCTION":true,"MODULE_EXTENSIONS":".min.js|.js","MODULE_MINIFICATION_LEVEL":"ESPRIMA","MODULE_URL":"http://www.espruino.com/modules","NPM_MODULES":false,"RESET_BEFORE_SEND":true,"SAVE_ON_SEND":"1","SERIAL_AUDIO":"0","SERIAL_TCPIP":"","SERIAL_THROTTLE_SEND":false,"SET_TIME_ON_WRITE":true,"SHOW_CODE_LINK_ICON":false,"SHOW_WEBCAM_ICON":0,"STORE_LINE_NUMBERS":true,"Sound_Error":"sirens_x","Sound_Info":"truck_horn","Sound_Success":"doorbell2","Sound_Warning":"trolley2","Speak_Error":false,"Speak_Info":false,"Speak_Success":false,"Speak_Warning":false,"UI_MODE":"Normal"}
Initialising SettingsConsole
Initialising Utils
Initialising Config
Initialising Notifications
Initialising Status
Initialising App
Initialising File
Initialising Code
Initialising Serial
  - Initialising Serial Chrome Serial
  - Initialising Serial Chrome Socket
  - Initialising Serial Audio
Initialising Terminal
Initialising CodeWriter
Initialising Modules
Initialising Env
Initialising Flasher
Initialising EditorBlockly
Initialising EditorJavaScript
Initialising Send
Initialising MenuPortSelector
Initialising MenuSettings
Initialising MenuFlasher
Initialising SettingsAbout
Initialising SettingsFlasher
Initialising BoardJSON
Initialising VersionChecker
Initialising Compiler
Initialising Assembler
Initialising GetGitHub
Initialising NPMModules
Initialising ExamplePlugin
Initialising Unicode
Initialising SaveOnSend
Initialising Minify
Initialising Tutorial
Initialising Webcam
Initialising FontSize
Initialising UiMode
Initialising URLHandler
Initialising CodeLink
Initialising Project
Initialising Testing
Initialising Notification_Sound
Initialising Tern
Initialising Debugger
Initialising Tour
Initialising SettingsProfile
Initialising HelpLinks
Loaded code from storage.
>>> Connecting...
Set Slow Write = true
[object Object]
Connected [object Object]
Found a prompt... great!
>>> Sending...
---> "\u0010console.log(\"<\",\"<<\",JSON.stringify(process.env),\">>\",\">\")\n"
>>> Sent
WARNING: No result found - just got ""
Device found (connectionId=5)
[success] Connected to port COM3
>>> Connected to port COM3
```
but since i cannot type in the prompt nor upload any code ...

**Comment by MaBecker** [comment]
try to upload some lines of code and check again the log

**Comment by michapixel** [comment]
```
FileWriter: truncating
FileWriter: writing
FileWriter: complete
Save on send transformed code to: E.setBootCode("setTime(1486242862.613);\nvar  on = false;\nsetInterval(function() {\n  on = !on;\n  LED1.write(on);\n}, 500);");load(); 
Found a prompt... great!
>>> Sending...
---> "\u0010reset();\n\u0010E.setBootCode(\"setTime(1486242862.613);\\nvar  on = false;\\nsetInterval(function() {\\n  on = !on;\\n  LED1.write(on);\\n}, 500);\");load();\n\n"
Splitting at "reset();\n", delay 250
>>> Sent
```
shouldn't it spit out the "boot logo" or something?
and it doesn't blink, so i guess it doesn't work :-)

**Comment by MaBecker** [comment]
yep - what do you see when you press the reset button ?

**Comment by michapixel** [comment]
sd$Ü<là<läc|är#cûgndogãäc8lrd;lpûgàlcnâ|cûg'çlÄd`gl o;ÛgÛl`xûoà;ãà#gã|äÇcû'oîd`ogl n{gÇlxóoà{ãàäl#gã|Äcûgnçl`ngl`'{gl s'd`;loÜÄò'oßÄã;og'$#$älìl$l~;lìddlgâ$llläloàgä'dlàÀcäÄllxcc{äl 'dpäd`cl lonãgd|c$d`;lãäoì;ûg|ìld`ã;$þLoading 7732 bytes from flash...
main ...
sdlÜ<là<läc|ìr#cûgndogâäc8älsd;lpûgàlcoâ|cûg'çlÄd`'l`o;ÇÛ'Ûd`8ûoà;Üãàb'ã|äcû'oîd`ogl n;ÛgÇlxóoà;ãàìl#gã|Äcûgnîl`ogl n{gl`snd`rlÄoÜÄònoßÄã;ogn$blälìlllrlìddl'â$llläloàgä'dlàÀcäÄllxcc{äl 'dpäd`cl lgßnãgd|#$d`;lÄãänì{ûo|äll`ã{dþLoading 7732 bytes from flash...
main ...

**Comment by MaBecker** [comment]
bingo !

format of save code is different between version

use esptool.py and command erase_flash

that flash again

**Comment by michapixel** [comment]
Aye, that worked well. Thank you so much. 

Does that mean save code (like wifi.save()) stored with older (or newer) versions isn't compatible?
Well good to know how to erase than ;-)

**Comment by MaBecker** [comment]
erase_flash will erase everything.

there is a additional command named `erase_region` to wipe section where Espruino save code

    esptool.py erase_region -h

**Comment by michapixel** [comment]
hmmm, seems to be missing in my version:
```
esptool: error: argument operation: invalid choice: 'erase_region' (choose from 'load_ram', 'dump_mem', 'read_mem', 'write_mem', 'write_flash', 'run', 'image_info', 'make_image', 'elf2image', 'read_mac', 'chip_id', 'flash_id', 'read_flash', 'verify_flash', 'erase_flash', 'version')
```
where
```
$ esptool.py version
esptool.py v1.3
1.3
```

**Comment by MaBecker** [comment]
$ esptool.py version
    esptool.py v2.0-beta1
    2.0-beta1

**Comment by MaBecker** [comment]
now WebIDE and node version should work

**Comment by michapixel** [comment]
https://www.youtube.com/watch?v=p8mdq6fzzYM ;-)

how do i upgrade esptool to that beta?

**Comment by MaBecker** [comment]
I downloaded esptool.py with `git clone` and used `git pull` to update

check this repository https://github.com/espressif/esptool.git how to

**Comment by michapixel** [comment]
a, now i got it ;-)

i flashed again and it worked. Even te WebIDE responded properly. 
So i tried my first baby-steps-code:
```
const esp = require('ESP8266');
const intval_temp_measure = 5000 ; // every 5 second
let intval_temp_measure_id = null;
// PINS OLED
let pin_OLED_SCL = NodeMCU.D6; // grey
let pin_OLED_SDA = NodeMCU.D5; // white
// PINS SENSOR
let pin_DHT22 = NodeMCU.D7; // blue
// PRECONF
I2C1.setup({
	scl: pin_OLED_SCL,
	sda: pin_OLED_SDA
});
// 
let OLED = null;
// debugging
const trace = (o) => {
    console.log(o)
};
// FIX VARS
const DHT = require('DHT22').connect(pin_DHT22);
// VARS
let temp = null;
let rh = null;
// METHODS
const measureInterval = function() {
	DHT.read(function (a) {
		temp = a.temp.toString();
		lh = a.rh.toString();
                // check if it works
		trace(`Temp is ${temp} and Hum. is ${lh}`);
	});
};
// 
const test = function(){
	// write some text
	// g.setFontVector(20);
	// OLED.drawString("Hello World!", 2, 2);
	// write to the screen
	// OLED.flip();

}
// MAIN
const main = function() {
	trace('main ...')
};

const init = function() {
	trace(`temp-program start ...`);
	intval_temp_measure_id = setInterval(measureInterval, intval_temp_measure);
	measureInterval();
	// let options = { address : 0x3D };
	OLED = require("SSD1306").connect(I2C1, test);
}
setTimeout(init, 500);
```

but it fails :

```
espruino:  Uncaught InternalError: I2CWrite: No ACK 0
espruino:
espruino:   at line 2 col 6
[0,a])
espruino:       ^
espruino:  in function called from line 2 col 8
espruino:  [0,a])})
       ^
espruino:  in function called from system
```

bare with me, this is from npm, not the ide, as i cannot copy any code out of the console there ... it always looses focus, damn html5 ;-)

**Comment by michapixel** [comment]
Oh my ... Nevermind, i had SCL and SDA on the wrong pins ... i'm so sorry. 

It fucking Worked! 
Thanks so much man!

**Comment by MaBecker** [comment]
GREAT, glad to hear that everything is now working as suspected.

BTW it is no shame to asks those question and if you want to reach a large group of people, just post on  http://forum.espruino.com
